### ISSUE TITLE
Export or Save Animation as *.gif

### ISSUE THREAD

**Issue by bchwtz** [kcf-jackson/animate#8]
Thank you for putting in the effort to develop the package. Usage is convenient and the output looks great. Is there a suggested way to export animations as `*.gif`?

**Comment by kcf-jackson** [comment]
Thank you and yes, there is a way to export animation as `*.gif`, but unfortunately it requires a bit of work and currently working for Chrome only. The idea is to do a screencast with the browser and save it as MP4 video, then convert to GIF images using `ffmpeg`. Here are the steps:


#### 1. Launch the device with the browser
When you create the device, launch it with the browser, e.g., 
```
library(animate)
device <- animate$new(width = 500, height = 500, launch.browser = utils::browseURL)
```
(If your default browser is not Chrome, you can copy and paste the link from your default browser to Chrome. The device only communicates with the last connection, so it will be connected to the Chrome side.)


#### 2. Begin screencasting and run the animation

- Call `device::record()` and confirm "y" in R, then choose the tab / window / screen to "share" (which is screencasting in this context) at the browser end. This should look familiar if you have used Teams / Zoom Meetings.
- Once the sharing begins, switch to the editor and run the code that would produce the animation. 
- Next, go back to the browser to see until the animation ends, then click "Stop sharing" or anywhere outside the plotting area and a MP4 video will be saved to your browser's default Downloads directory. 

(When you record a tab or a window, it's fine to switch over to your editor and the switching won't show in the screencast.)


#### 3. Convert the MP4 video into GIF images using `ffmpeg`

The package has a "development" function `animate:::ffmpeg`, which will launch a Shiny app to do the conversion. It looks like this:
![image](https://github.com/kcf-jackson/animate/assets/12783172/999e1e56-15e8-4262-a583-0b9cf0393a66)

- The Shiny app is just an UI to construct and run the `ffmpeg` commands.
- Adjust the parameters and "preview" the output. When you are done, click the vertical 3 dots in the output panel to save the edited video, or right click "save as" to save the GIF image.
- Notes 
  - Conversion can take a little time. Don't start a conversion until the last one is complete. You can always look at the R console to see the progress. 
  - Conversion is still needed for MP4 video output to fix the frame rate and encoding.
  - In case of an error, restarting the app should fix it. If not, please open an issue. Thanks!


Hope it helps. Let me know if you encounter any issue.

**Comment by kcf-jackson** [comment]
Support for direct GIF generation has been added in v0.3.9.6, available through `remotes::install_github("kcf-jackson/animate")`. See the `screenshot` entry in `?animate::animate` for notes and examples. 

Note: There are limitations to converting vector graphics (SVG) to raster images (GIF), and screencasting is still the more reliable method for recording complex animation, albeit more difficult to create.

Please open an issue on GitHub if you encounter any issues while using this new feature. Thanks!
